[package]
name = "rustiest-boy"
version = "0.1.0"
authors = ["José Lico"]
description = "Yet another GameBoy emulator built in Rust"
license = "MIT"
repository = "https://github.com/jose-lico/rustiest-boy"
edition = "2021"

[dependencies]
sdl2 = { version = "0.35", default-features = false, features = ["ttf"] }
